stages:
  data_collection:
    cmd: python ./src/data_collection.py
    deps:
    - ./src/data_collection.py
    outs:
    - ./data/raw
  data_preparation:
    cmd: python ./src/data_preparation.py
    deps:
    - ./src/data_preparation.py
    outs:
    - ./data/processed
  modeling:
    cmd: python ./src/modeling_evaluation.py
    deps:
    - ./src/modeling_evaluation.py
    - ./data/processed
  registration:
    cmd: python ./src/model_register.py
    deps:
    - ./src/model_register.py
    - ./backend/models/run_info.json


